Revert "Cleanup: add semicolon after PyObject_VAR_HEAD"
This reverts commit 8f9479ae6223d55ae24b339921e29edfc0e26b46.

This causes MSVC2019 build to fail with error C2059

Unfortunately this means we have to put up with bad formatting
in Python structs.