Revert "Cleanup: add semicolon after PyObject_VAR_HEAD"
This reverts commit 472dadbe3dd7315fea029f8bbe0a91aaf583a832.

This causes MSVC2019 build to fail with error C2059

Unfortunately this means we have to put up with bad formatting
in Python structs.