Windows: Compile error due to missing header
Caused by bae7c91238
Error: `undeclared identifier M_PI and M_PI_2`

Pull Request: https://projects.blender.org/blender/blender/pulls/118185