Revert "CMake: quiet warnings with 3.0"
This reverts commit da7bdf1b47d4490c1a6f35740a9392cb9b5dd42e.

This broke compilation in OSX and some Linux boxes.
Error:  Policy "CMP0043" is not known to this version of CMake

Shall we leave those for after RC (or even 2.71) is out? ;)